class FeatureCodes:
    add_ons = 'AO'
    custom_question = 'CQ'
    donation = 'DO'
    eventbrite_studio = 'ES'
    facebook = 'FB'
    group_registration = 'GR'
    repeating_events = 'RE'
    reserved_seating = 'RS'
    wait_list = 'WL'
    website_widgets = 'WW'
