# Generated by Django 3.0.5 on 2020-05-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_events_app', '0002_auto_20200427_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='alpha_3_code',
        ),
        migrations.RemoveField(
            model_name='country',
            name='flag',
        ),
        migrations.AddField(
            model_name='country',
            name='eventbrite_id',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
    ]
