# Generated by Django 3.0.5 on 2020-05-26 20:54

from django.db import migrations, models
import search_events_app.mixins.get_context_mixin


class Migration(migrations.Migration):

    dependencies = [
        ('search_events_app', '0007_populate_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
            bases=(models.Model, search_events_app.mixins.get_context_mixin.GetContextMixin),
        ),
    ]
